source:      .
destination: ./_site
includes:    ./_includes
url: "http://rapid-pooch.cloudvent.com"

permalink:   /:title.html

#base_url: http://vlandham.com
#base_url: /
description: "Testing"

encoding: utf-8


defaults:
  -
    scope:
      path: ""
    values:
      ogtype: "website"
  -
    scope:
      path: ""
      type: "posts"
    values:
      ogtype: "article"
